# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 950d7459531ee2e149d1b776879b677c79f2d11608c86f1f15a2a3efe485cee5c40992484363e33c3e022705d87fb692cf6b85188b6d2283380b2d5cb2f65e76

test:
  secret_key_base: e8e9d41ffd2ce1b94e5b06d4677b8c37a0c9e61cfe50266b4808691a4fe06111baa4906fac2d98925e2b8fafc34a3c8c5d342dbecd16a3039c0b452e8b763fe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
